name: All Contributors
on:
  issue_comment:
    types: [created]

jobs:
  add-contributor:
    if: |
      github.event.issue.pull_request == '' &&
      contains(github.event.comment.body, '@all-contributors')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: all-contributors/add-contributor-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
